# Generated by Django 3.1.5 on 2021-01-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='PaidAttendenceCertificateDL',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='PaidAttendenceCertificatePython',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='PaidAttendenceDL',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='PaidAttendencePython',
            field=models.BooleanField(default=False),
        ),
    ]
