# Generated by Django 3.1.5 on 2021-01-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210127_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='PaidAttendenceCertificatePython',
            field=models.BooleanField(default=True),
        ),
    ]
