# Generated by Django 3.1.5 on 2021-01-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210127_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='PaidAttendenceDL',
            field=models.BooleanField(default=True),
        ),
    ]
