# Generated by Django 3.1.1 on 2021-01-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20210127_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='PaidAttendenceCertificatePython',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='PaidAttendenceDL',
            field=models.BooleanField(default=False),
        ),
    ]
