# Generated by Django 3.1.5 on 2021-01-29 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20210127_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='enrolledStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.CharField(max_length=100)),
                ('OrderId', models.CharField(max_length=100)),
                ('PaymentId', models.CharField(max_length=100)),
                ('Signature', models.CharField(max_length=100)),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('enrolled_stud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
